[build]
  command = "next build && next export"
  publish = "out/"
  functions = "out_functions/"
  environment = { NODE_ENV = "production" }

# Redirect all traffic to the index.html (common for SPAs)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
